/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: the API and its database both answer. The keep-alive cron calls this, which also keeps the
         *     Supabase free project from pausing after 7 idle days.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process answers, without touching the database. Render's health check uses this, so a
         *     database outage doesn't make Render restart or refuse to deploy the API.
         */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Products
         * @description Catalog search. Without `sort`, results are ranked: exact designation, prefix, contains, dimension match,
         *     word match; then natural designation order. A page past the end returns the last page (see `meta.page`).
         */
        get: operations["search_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Stats */
        get: operations["product_stats_api_v1_products_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/sitemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Sitemap
         * @description Slugs in catalog order with their last import time, one sitemap file at a time.
         */
        get: operations["product_sitemap_api_v1_products_sitemap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Related Products
         * @description Same type, closest bore diameter first.
         */
        get: operations["related_products_api_v1_products__slug__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/industries/{slug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Industry Products
         * @description Products used in an industry, B&B Unikoop's own picks first. An unknown industry has none.
         */
        get: operations["industry_products_api_v1_industries__slug__products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Specs
         * @description SKF technical data: load ratings, speeds, mass, calculation factors and the full data sheet.
         *     404 `specs_not_found` when the product has none: link to `https://www.skf.com` instead of guessing values.
         */
        get: operations["product_specs_api_v1_products__slug__specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/decode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Decode Designation
         * @description Splits an SKF designation (6205-2RSH/C3, 22212 EK, NU 208 ECP) into prefix, series, bore code and suffixes.
         */
        get: operations["decode_designation_api_v1_catalog_decode_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/greases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Grease Guide */
        get: operations["grease_guide_api_v1_catalog_greases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/rating-life": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rating Life
         * @description ISO 281 basic rating life L10 and the life at a higher reliability (a1), for a catalog product or a given C.
         *     Loads in kN. Errors: `rating_life_unsupported` (not a rolling bearing), `load_case_unsupported` (e.g. an axial
         *     load without SKF factors).
         */
        get: operations["rating_life_api_v1_catalog_rating_life_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/relubrication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relubrication
         * @description SKF's simplified grease relubrication interval and replenishment quantity. Errors: `relubrication_unsupported`,
         *     `relubrication_out_of_range` (too fast for grease).
         */
        get: operations["relubrication_api_v1_catalog_relubrication_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description A chat turn, streamed. Starter prompts (`preset`) are answered from catalog data without the model; free
         *     text goes to the model with the catalog tools. Limits: 10 messages per 10 min per client, 2,000 characters.
         */
        post: operations["chat_api_v1_assistant_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback
         * @description Thumbs up/down on an answer (`messageId` from its `done` event). Sending again replaces it.
         */
        post: operations["feedback_api_v1_assistant_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AskEvent
         * @description A scripted flow asks the user for input; the next message answers it.
         */
        AskEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ask";
            /**
             * Ask
             * @enum {string}
             */
            ask: "product_query" | "designation" | "grease_conditions";
        };
        /**
         * ChatImage
         * @description A photo sent with the message, e.g. of a bearing's markings or its box. Only passed to the model, never
         *     stored. The widget sends JPEGs of at most 1600 px.
         */
        ChatImage: {
            /**
             * Mimetype
             * @enum {string}
             */
            mimeType: "image/jpeg" | "image/png" | "image/webp";
            /**
             * Data
             * @description Base64, without a data: prefix
             */
            data: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Conversationid
             * @description From a previous `done` event; omit to start
             */
            conversationId?: string | null;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Preset
             * @description A starter prompt's flow. With an empty message the flow asks for what it needs
             */
            preset?: ("product_search" | "datasheet" | "decode" | "grease" | "where_to_buy") | null;
            /**
             * Locale
             * @description Site language; the answer follows the user's
             * @default mk
             */
            locale: string;
            /**
             * Images
             * @description Photos for the model; a message with photos skips the flows
             */
            images?: components["schemas"]["ChatImage"][];
        };
        /**
         * ConfidenceEvent
         * @description The model's own rating of its answer. None when the answer is a question back.
         */
        ConfidenceEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "confidence";
            /** Score */
            score: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "supported" | "bounded" | "partial" | "insufficient" | "conflicting" | "not_applicable";
            /** Reason */
            reason?: string | null;
        };
        /**
         * ContactEvent
         * @description Where to buy: B&B Unikoop's offices, phones and the contact form.
         */
        ContactEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "contact";
        };
        /** DatasheetRow */
        DatasheetRow: {
            /**
             * Name
             * @description SKF's name for the value, e.g. 'Shoulder diameter' (English)
             */
            name: string;
            /**
             * Symbol
             * @description Plain-text symbol, e.g. 'd1', 'C0', 'kr'
             */
            symbol?: string | null;
            /** Value */
            value?: number | string | null;
            /**
             * Min
             * @description For a range, e.g. a tolerance
             */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Unit */
            unit?: string | null;
            /**
             * Qualifier
             * @description '≈' for approximate values
             */
            qualifier?: string | null;
        };
        /** DatasheetSection */
        DatasheetSection: {
            /**
             * Title
             * @description e.g. 'Dimensions', 'Abutment dimensions', 'Calculation data', 'Properties'
             */
            title: string;
            /** Rows */
            rows: components["schemas"]["DatasheetRow"][];
        };
        /** DecodeEvent */
        DecodeEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "decode";
            decoded: components["schemas"]["DecodedDesignation"];
        };
        /**
         * DecodedDesignation
         * @description An empty `segments` list means nothing could be read (blank or separators only).
         */
        DecodedDesignation: {
            /** Designation */
            designation: string;
            /** Segments */
            segments: components["schemas"]["DesignationSegment"][];
            /** Boremm */
            boreMm: number | null;
        };
        /** DesignationSegment */
        DesignationSegment: {
            /**
             * Token
             * @description The part as typed, e.g. '62', '05', '2RSH'
             */
            token: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "prefix" | "series" | "bore" | "suffix" | "unknown";
            /**
             * Id
             * @description Meaning key (frontend `Decoder.codes.<id>`); null for unknown parts
             */
            id: string | null;
            /**
             * Boremm
             * @description Bore diameter for a bore segment, mm
             */
            boreMm: number | null;
        };
        /**
         * DoneEvent
         * @description Always the last event of a turn that was saved: keep `conversationId` for the next message and `messageId`
         *     for feedback.
         */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /**
             * Conversationid
             * Format: uuid
             */
            conversationId: string;
            /**
             * Messageid
             * Format: uuid
             */
            messageId: string;
        };
        /**
         * ErrorEvent
         * @description assistant_unavailable: no model configured or every model down; assistant_busy: the daily limit is used up;
         *     assistant_failed: the answer broke off; conversation_not_found: start a new one.
         */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /**
             * Code
             * @enum {string}
             */
            code: "assistant_unavailable" | "assistant_busy" | "assistant_failed" | "conversation_not_found";
            /** Detail */
            detail: string;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Messageid
             * Format: uuid
             * @description From the answer's `done` event
             */
            messageId: string;
            /**
             * Rating
             * @enum {string}
             */
            rating: "up" | "down";
            /** Reason */
            reason?: ("incorrect" | "not_what_i_asked" | "slow_or_buggy" | "style" | "safety" | "other") | null;
            /** Comment */
            comment?: string | null;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** GreaseChartRow */
        GreaseChartRow: {
            /** Code */
            code: string;
            /**
             * Tempc
             * @description Operating temperature range, °C
             */
            tempC: [
                number,
                number
            ];
            /**
             * Viscosity
             * @description Base oil viscosity at 40 °C, mm²/s
             */
            viscosity: number;
            /**
             * Temp
             * @description Temperature level: L, M, H, VH (ranges like 'L–M')
             */
            temp: string;
            /**
             * Speed
             * @description Speed level: VL, L, M, H, EH
             */
            speed: string;
            /**
             * Load
             * @description Load level: L, M, H, VH
             */
            load: string;
            /**
             * Fit
             * @description One mark per `columns` entry: + recommended, o suitable, - not
             */
            fit: ("+" | "o" | "-")[];
        };
        /** GreaseCompatibility */
        GreaseCompatibility: {
            /**
             * Groups
             * @description Greases in one group behave the same, e.g. 'LGMT 2 · LGMT 3'
             */
            groups: string[];
            /**
             * Matrix
             * @description matrix[row][col]: + compatible, - not, = same grease
             */
            matrix: ("+" | "-" | "=")[][];
        };
        /**
         * GreaseGuide
         * @description SKF bearing grease selection: the basic choice per condition, the selection chart and compatibility.
         */
        GreaseGuide: {
            /** Basic */
            basic: components["schemas"]["GreaseRecommendation"][];
            /** Columns */
            columns: ("verticalShaft" | "outerRing" | "oscillating" | "vibration" | "shockLoad" | "rust")[];
            /** Chart */
            chart: components["schemas"]["GreaseChartRow"][];
            compatibility: components["schemas"]["GreaseCompatibility"];
        };
        /** GreaseRecommendation */
        GreaseRecommendation: {
            /**
             * Condition
             * @enum {string}
             */
            condition: "allPurpose" | "highTemp" | "extremeTemp" | "lowTemp" | "highLoad" | "food" | "green";
            /** Code */
            code: string;
        };
        /**
         * GreasesEvent
         * @description The basic SKF grease choice per condition; the full chart is on /products/greases.
         */
        GreasesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "greases";
            /** Basic */
            basic: components["schemas"]["GreaseRecommendation"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @constant
             */
            database: "ok";
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** PageMeta */
        PageMeta: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Pages */
            pages: number;
        };
        /** Page[Product] */
        Page_Product_: {
            /** Data */
            data: components["schemas"]["Product"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Problem */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
        };
        /**
         * Product
         * @description A catalog row. Dimensions use SKF's notation: d = bore, D = outside diameter, B = width (all mm).
         */
        Product: {
            /** Slug */
            slug: string;
            /** Designation */
            designation: string;
            /** Brand */
            brand: string;
            /** Type */
            type: string;
            /** Classification */
            classification: string | null;
            /** D */
            d: number | null;
            /** D */
            D: number | null;
            /** B */
            B: number | null;
            /** Seal */
            seal: ("open" | "shields" | "both" | "one-side" | "other") | null;
            /** Boretype */
            boreType: ("cylindrical" | "tapered") | null;
            /** Industries */
            industries: string[];
        };
        /** ProductList */
        ProductList: {
            /** Data */
            data: components["schemas"]["Product"][];
        };
        /**
         * ProductSpecs
         * @description SKF technical data for a product. Loads in kN, speeds in r/min, mass in kg.
         */
        ProductSpecs: {
            /** Slug */
            slug: string;
            /**
             * C
             * @description Basic dynamic load rating C, kN
             */
            c: number | null;
            /**
             * C0
             * @description Basic static load rating C0, kN
             */
            c0: number | null;
            /**
             * Pu
             * @description Fatigue load limit Pu, kN
             */
            pu: number | null;
            /**
             * Referencespeed
             * @description r/min
             */
            referenceSpeed: number | null;
            /**
             * Limitingspeed
             * @description r/min
             */
            limitingSpeed: number | null;
            /**
             * Mass
             * @description kg
             */
            mass: number | null;
            /**
             * Performanceclass
             * @description e.g. 'SKF Explorer'
             */
            performanceClass: string | null;
            /**
             * Factors
             * @description Calculation factors by symbol: kr, f0, e, Y, Y0, Y1, Y2, ...
             */
            factors: {
                [key: string]: number;
            };
            /** Datasheet */
            datasheet: components["schemas"]["DatasheetSection"][];
            /**
             * Sourceurl
             * @description The product's page on skf.com
             */
            sourceUrl: string | null;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
        };
        /** ProductStats */
        ProductStats: {
            /** Count */
            count: number;
            /**
             * Updatedat
             * @description When the catalog was last imported
             */
            updatedAt: string | null;
        };
        /**
         * ProductsEvent
         * @description Product cards. `search` is set by the search flow: link to /catalog?search=<search> for all `total`.
         */
        ProductsEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "products";
            /** Products */
            products: components["schemas"]["Product"][];
            /** Total */
            total?: number | null;
            /** Search */
            search?: string | null;
        };
        /**
         * RatingLife
         * @description ISO 281 basic rating life, without the SKF life modification factor (aSKF = 1).
         */
        RatingLife: {
            /**
             * Designation
             * @description When computed for a catalog product
             */
            designation: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "deep-groove" | "angular-contact" | "self-aligning" | "thrust-ball" | "unit" | "cylindrical-roller" | "spherical-roller" | "tapered-roller" | "needle-roller" | "toroidal";
            /**
             * C
             * @description kN
             */
            c: number;
            /**
             * P
             * @description Equivalent dynamic load P = x·Fr + y·Fa, kN
             */
            p: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /**
             * E
             * @description Fa/Fr limit that selected x and y
             */
            e: number | null;
            /**
             * Exponent
             * @description 3 for ball bearings, 10/3 for roller bearings
             */
            exponent: number;
            /**
             * L10
             * @description Basic rating life, million revolutions
             */
            l10: number;
            /**
             * L10Hours
             * @description Basic rating life, operating hours
             */
            l10Hours: number;
            /**
             * Reliability
             * @enum {integer}
             */
            reliability: 90 | 95 | 96 | 97 | 98 | 99;
            /** A1 */
            a1: number;
            /**
             * Lnm
             * @description Life at the requested reliability, million revolutions
             */
            lnm: number;
            /**
             * Lnmhours
             * @description Life at the requested reliability, operating hours
             */
            lnmHours: number;
            /**
             * Warnings
             * @description heavy_load: P > 0.5 C, outside the equation's range; above_limiting_speed: rpm > SKF's limit
             */
            warnings: ("heavy_load" | "above_limiting_speed")[];
        };
        /**
         * Relubrication
         * @description SKF's simplified relubrication interval for a lithium-base grease. An estimate: conditions like
         *     contamination, water or vibration shorten it.
         */
        Relubrication: {
            /** Designation */
            designation: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "deep-groove" | "angular-contact" | "self-aligning" | "unit" | "cylindrical-roller" | "needle-roller" | "spherical-roller" | "tapered-roller" | "thrust-ball";
            /** D */
            d: number;
            /**
             * K
             * @description Bearing type factor: 10 ball, 5 cylindrical/needle roller, 1 other roller/thrust
             */
            k: number;
            /**
             * Basehours
             * @description Interval at 70 °C on a horizontal shaft, operating hours
             */
            baseHours: number;
            /**
             * Hours
             * @description Interval for the given temperature and shaft, at most 30,000 h
             */
            hours: number;
            /**
             * Capped
             * @description The formula gave more than 30,000 h
             */
            capped: boolean;
            /**
             * Greasesideg
             * @description Replenishment from the side, 0.005·D·B, g
             */
            greaseSideG: number | null;
            /**
             * Greasecenterg
             * @description Replenishment through the outer ring, 0.002·D·B, g
             */
            greaseCenterG: number | null;
        };
        /** SitemapRow */
        SitemapRow: {
            /** Slug */
            slug: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SitemapRows */
        SitemapRows: {
            /** Data */
            data: components["schemas"]["SitemapRow"][];
        };
        /** Source */
        Source: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** SourcesEvent */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
            /** Sources */
            sources: components["schemas"]["Source"][];
        };
        /**
         * SpecsEvent
         * @description A product's data sheet. `specs` is null when SKF data isn't in the catalog yet: link to skf.com.
         */
        SpecsEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "specs";
            product: components["schemas"]["Product"];
            specs: components["schemas"]["ProductSpecs"] | null;
        };
        /**
         * StatusEvent
         * @description What the assistant is doing, until the first text arrives.
         */
        StatusEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "status";
            /**
             * Status
             * @enum {string}
             */
            status: "thinking" | "searching" | "reading" | "calculating";
        };
        /**
         * SuggestionsEvent
         * @description Follow-up questions the user may ask next, in the user's language. A click sends one as the next message.
         */
        SuggestionsEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "suggestions";
            /** Suggestions */
            suggestions: string[];
        };
        /**
         * TextEvent
         * @description A piece of the model's Markdown answer; append in order.
         */
        TextEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search_products_api_v1_products_get: {
        parameters: {
            query?: {
                /** @description Designation (6205-2RSH, 62052rsh, 62…), dimensions (25x52x15, 25 52) or words in `locale` */
                search?: string;
                /** @description Language of the search words. Unknown locales fall back to mk */
                locale?: string;
                type?: string | null;
                bore?: string | null;
                seal?: string | null;
                /** @description Products used in any of these industries */
                industry?: string[];
                dmin?: number | null;
                dmax?: number | null;
                Dmin?: number | null;
                Dmax?: number | null;
                Bmin?: number | null;
                Bmax?: number | null;
                /** @description Default: relevance, then designation */
                sort?: ("designation" | "type" | "boreType" | "seal" | "d" | "D" | "B") | null;
                dir?: "asc" | "desc";
                /** @description 1-based page number */
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Product_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_stats_api_v1_products_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStats"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_sitemap_api_v1_products_sitemap_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapRows"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_product_api_v1_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description No product with this slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    related_products_api_v1_products__slug__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description No product with this slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    industry_products_api_v1_industries__slug__products_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_specs_api_v1_products__slug__specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSpecs"];
                };
            };
            /** @description No technical data for this product (yet) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    decode_designation_api_v1_catalog_decode_get: {
        parameters: {
            query: {
                designation: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecodedDesignation"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    grease_guide_api_v1_catalog_greases_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GreaseGuide"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    rating_life_api_v1_catalog_rating_life_get: {
        parameters: {
            query: {
                slug?: string | null;
                type?: ("deep-groove" | "angular-contact" | "self-aligning" | "thrust-ball" | "unit" | "cylindrical-roller" | "spherical-roller" | "tapered-roller" | "needle-roller" | "toroidal") | null;
                /** @description Basic dynamic load rating, kN */
                c?: number | null;
                /** @description Radial load, kN */
                fr?: number;
                /** @description Axial load, kN */
                fa?: number;
                /** @description Rotational speed, r/min */
                rpm: number;
                /** @description %, for the a1 factor (ISO 281) */
                reliability?: 90 | 95 | 96 | 97 | 98 | 99;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatingLife"];
                };
            };
            /** @description `product_not_found`, or `specs_not_found` (no load rating yet) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid fields, or a case the formulas don't cover (`load_case_unsupported`, ...) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    relubrication_api_v1_catalog_relubrication_get: {
        parameters: {
            query: {
                slug?: string | null;
                type?: ("deep-groove" | "angular-contact" | "self-aligning" | "unit" | "cylindrical-roller" | "needle-roller" | "spherical-roller" | "tapered-roller" | "thrust-ball") | null;
                /** @description Bore diameter, mm */
                d?: number | null;
                /** @description Outside diameter, mm */
                D?: number | null;
                /** @description Width, mm */
                B?: number | null;
                /** @description Rotational speed, r/min */
                rpm: number;
                /** @description Operating temperature, °C */
                temperature?: number;
                verticalShaft?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Relubrication"];
                };
            };
            /** @description `product_not_found`, or `specs_not_found` (no load rating yet) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid fields, or a case the formulas don't cover (`load_case_unsupported`, ...) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    chat_api_v1_assistant_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description JSON Lines: one event per line, ending with `done` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/jsonl": unknown;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description `rate_limited` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    feedback_api_v1_assistant_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description `rate_limited` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
