/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Readiness: the API and its database both answer. The keep-alive cron calls this, which also keeps the
         *     Supabase free project from pausing after 7 idle days.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Liveness: the process answers, without touching the database. Render's health check uses this, so a
         *     database outage doesn't make Render restart or refuse to deploy the API.
         */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Products
         * @description Catalog search. Without `sort`, results are ranked: exact designation, prefix, contains, dimension match,
         *     word match; then natural designation order. A page past the end returns the last page (see `meta.page`).
         */
        get: operations["search_products_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Stats */
        get: operations["product_stats_api_v1_products_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/sitemap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Sitemap
         * @description Slugs in catalog order with their last import time, one sitemap file at a time.
         */
        get: operations["product_sitemap_api_v1_products_sitemap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_v1_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Related Products
         * @description Same type, closest bore diameter first.
         */
        get: operations["related_products_api_v1_products__slug__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/industries/{slug}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Industry Products
         * @description Products used in an industry, B&B Unikoop's own picks first. An unknown industry has none.
         */
        get: operations["industry_products_api_v1_industries__slug__products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}/specs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Product Specs
         * @description SKF technical data: load ratings, speeds, mass, calculation factors and the full data sheet.
         *     404 `specs_not_found` when the product has none: link to `https://www.skf.com` instead of guessing values.
         */
        get: operations["product_specs_api_v1_products__slug__specs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DatasheetRow */
        DatasheetRow: {
            /**
             * Name
             * @description SKF's name for the value, e.g. 'Shoulder diameter' (English)
             */
            name: string;
            /**
             * Symbol
             * @description Plain-text symbol, e.g. 'd1', 'C0', 'kr'
             */
            symbol?: string | null;
            /** Value */
            value?: number | string | null;
            /**
             * Min
             * @description For a range, e.g. a tolerance
             */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Unit */
            unit?: string | null;
            /**
             * Qualifier
             * @description '≈' for approximate values
             */
            qualifier?: string | null;
        };
        /** DatasheetSection */
        DatasheetSection: {
            /**
             * Title
             * @description e.g. 'Dimensions', 'Abutment dimensions', 'Calculation data', 'Properties'
             */
            title: string;
            /** Rows */
            rows: components["schemas"]["DatasheetRow"][];
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Database
             * @constant
             */
            database: "ok";
        };
        /** Liveness */
        Liveness: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** PageMeta */
        PageMeta: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Perpage */
            perPage: number;
            /** Pages */
            pages: number;
        };
        /** Page[Product] */
        Page_Product_: {
            /** Data */
            data: components["schemas"]["Product"][];
            meta: components["schemas"]["PageMeta"];
        };
        /** Problem */
        Problem: {
            /**
             * Type
             * @default about:blank
             */
            type: string;
            /** Title */
            title: string;
            /** Status */
            status: number;
            /** Code */
            code: string;
            /** Detail */
            detail?: string | null;
            /** Instance */
            instance?: string | null;
            /** Errors */
            errors?: components["schemas"]["FieldError"][] | null;
        };
        /**
         * Product
         * @description A catalog row. Dimensions use SKF's notation: d = bore, D = outside diameter, B = width (all mm).
         */
        Product: {
            /** Slug */
            slug: string;
            /** Designation */
            designation: string;
            /** Brand */
            brand: string;
            /** Type */
            type: string;
            /** Classification */
            classification: string | null;
            /** D */
            d: number | null;
            /** D */
            D: number | null;
            /** B */
            B: number | null;
            /** Seal */
            seal: ("open" | "shields" | "both" | "one-side" | "other") | null;
            /** Boretype */
            boreType: ("cylindrical" | "tapered") | null;
            /** Industries */
            industries: string[];
        };
        /** ProductList */
        ProductList: {
            /** Data */
            data: components["schemas"]["Product"][];
        };
        /**
         * ProductSpecs
         * @description SKF technical data for a product. Loads in kN, speeds in r/min, mass in kg.
         */
        ProductSpecs: {
            /** Slug */
            slug: string;
            /**
             * C
             * @description Basic dynamic load rating C, kN
             */
            c: number | null;
            /**
             * C0
             * @description Basic static load rating C0, kN
             */
            c0: number | null;
            /**
             * Pu
             * @description Fatigue load limit Pu, kN
             */
            pu: number | null;
            /**
             * Referencespeed
             * @description r/min
             */
            referenceSpeed: number | null;
            /**
             * Limitingspeed
             * @description r/min
             */
            limitingSpeed: number | null;
            /**
             * Mass
             * @description kg
             */
            mass: number | null;
            /**
             * Performanceclass
             * @description e.g. 'SKF Explorer'
             */
            performanceClass: string | null;
            /**
             * Factors
             * @description Calculation factors by symbol: kr, f0, e, Y, Y0, Y1, Y2, ...
             */
            factors: {
                [key: string]: number;
            };
            /** Datasheet */
            datasheet: components["schemas"]["DatasheetSection"][];
            /**
             * Sourceurl
             * @description The product's page on skf.com
             */
            sourceUrl: string | null;
            /**
             * Fetchedat
             * Format: date-time
             */
            fetchedAt: string;
        };
        /** ProductStats */
        ProductStats: {
            /** Count */
            count: number;
            /**
             * Updatedat
             * @description When the catalog was last imported
             */
            updatedAt: string | null;
        };
        /** SitemapRow */
        SitemapRow: {
            /** Slug */
            slug: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SitemapRows */
        SitemapRows: {
            /** Data */
            data: components["schemas"]["SitemapRow"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Liveness"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    search_products_api_v1_products_get: {
        parameters: {
            query?: {
                /** @description Designation (6205-2RSH, 62052rsh, 62…), dimensions (25x52x15, 25 52) or words in `locale` */
                search?: string;
                /** @description Language of the search words. Unknown locales fall back to mk */
                locale?: string;
                type?: string | null;
                bore?: string | null;
                seal?: string | null;
                /** @description Products used in any of these industries */
                industry?: string[];
                dmin?: number | null;
                dmax?: number | null;
                Dmin?: number | null;
                Dmax?: number | null;
                Bmin?: number | null;
                Bmax?: number | null;
                /** @description Default: relevance, then designation */
                sort?: ("designation" | "type" | "boreType" | "seal" | "d" | "D" | "B") | null;
                dir?: "asc" | "desc";
                /** @description 1-based page number */
                page?: number;
                perPage?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_Product_"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_stats_api_v1_products_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductStats"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_sitemap_api_v1_products_sitemap_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SitemapRows"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    get_product_api_v1_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
            /** @description No product with this slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    related_products_api_v1_products__slug__related_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description No product with this slug */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    industry_products_api_v1_industries__slug__products_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductList"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    product_specs_api_v1_products__slug__specs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductSpecs"];
                };
            };
            /** @description No technical data for this product (yet) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": unknown;
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
